### PR TITLE
Update bitcoin_zh_CN.ts

### PR DESCRIPTION
**Pull request by Mercedes-li**
更新Bunkercoin在中文的显示问题。
Update the display problem of Bunkercoin in Chinese.

### CODE REVIEW

**Review by sys-256 — APPROVED** [review]
I dont speak chinese but looks good to me.

**Comment by shruuub** [comment]
I dont speak it either, but throwing it into a translater, seems pretty gud

**Review by shruuub — APPROVED** [review]
roc approve!

**Comment by IdotMaster1** [comment]
@Mercedes-li are you Chinese/Know Chinese?

**Comment by IdotMaster1** [comment]
Also I cant approve this. It is pushing into the Master branch, please set it to push to 1.15.2-dev!

**Comment by sys-256** [comment]
> Also I cant approve this. It is pushing into the Master branch, please set it to push to 1.15.2-dev!

I changed the base branch. Ready to merge?

**Comment by Mercedes-li** [comment]
> @Mercedes-li你是中国人/懂中国人吗？

Yes, I am Chinese.

**Pull request merged**
